### ISSUE TITLE
Child theme

### ISSUE THREAD

**Issue by anna-vanlee** [andersnoren/poe#1]
hello
please tell me how to make a child theme for this theme?
I'm not a programmer and I'm afraid to do something wrong (
Thanks

**Comment by andersnoren** [comment]
I've attached a Poe child theme that you can use as a foundation. You can find more information about child themes here: https://developer.wordpress.org/themes/advanced-topics/child-themes/

[poe-child.zip](https://github.com/andersnoren/poe/files/9703998/poe-child.zip)

**Comment by anna-vanlee** [comment]
thank you very much
I installed a theme and a child theme on the site
and drew attention to the fact that if in the main theme you can select styles (one of twelve) by simply clicking on the style button, then this is not the case in the nursery, and you can adjust the styles of colors and layout by palette or by elements (separately background, text and links)
is this how it should be?
Or until child themes support all the functionality of the main themes?

and if you can and find the time, please post a children's theme for tove.
all your themes are beautiful, but tove is older and probably more reliable.
Thanks

**Comment by anna-vanlee** [comment]
![16648993691192882048182661952982](https://user-images.githubusercontent.com/10595887/193868970-5aa17805-1b5f-4e5f-ba3c-4a2f1c2585e7.jpg)

![Uploading 16648993974178003472684217606280.jpg…]()

**Comment by anna-vanlee** [comment]
![Uploading IMG-20221004-WA0042.jpeg…]()

**Comment by andersnoren** [comment]
> is this how it should be?

Yes, style variations in the parent theme will still be selectable when you're running a child theme.

> and if you can and find the time, please post a children's theme for tove.

You can change it from a Poe child theme to a Tove child theme by opening the style.css file in the theme folder and replacing "poe" with "tove".

> all your themes are beautiful, but tove is older and probably more reliable.

I would actually say Poe is more reliable, since it has quite a lot less custom CSS than Tove and will handle future WordPress updates better without requiring changes in the theme. But I'm glad you like it!
